### PR TITLE
[WIP] add GCStore using Google Cloud Storage REST API

### PR DESCRIPTION
**Pull request by Alexander-Barth**
Here is the promised PR for issue https://github.com/meggart/Zarr.jl/issues/71 .

Note that it uses URIs an additional dependency ([URIs](https://github.com/JuliaWeb/URIs.jl/blob/master/Project.toml) is pure Julia with no dependencies itself). Let me know if this OK for you, otherwise I can update the PR so that it does not use URIs.

The PR also works with URLs starting with `gs://`:

```julia
store, path = Zarr.storefromstring(GCStore,"gs://cmip6/CMIP6/CMIP/AS-RCEC/TaiESM1/1pctCO2/r1i1p1f1/Amon/hfls/gn/v20200225/",false)
zds = zopen(store,path=path)
```
But  `AnonymousGCS` is still the default for such URLs.

I can also contribute some additional information to the documentation.

### CODE REVIEW

**Review by meggart — APPROVED** [review]

**Comment by meggart** [comment]
Thanks a lot for preparing the PR. Do you know what is happening in the failing test?

**Comment by Alexander-Barth** [comment]
Indeed, there in an error with GCS. But I have same error when I run the current master (bbdc21a7b15d4fdcd124addcdb370c3e2b69f70d) without my PR. Strange ...
It seems HTML is returned when JSON was expected. I will have a look.



```
(@v1.6) pkg> test Zarr
     Testing Zarr
      Status `/tmp/jl_zsgJnf/Project.toml`
  [8f4d0f93] Conda v1.5.2
  [682c06a0] JSON v0.21.2
  [4281f0d9] Minio v0.1.2
  [438e738f] PyCall v1.92.5
  [0a941bbe] Zarr v0.7.0 `~/.julia/dev/Zarr`
  [ade2ca70] Dates `@stdlib/Dates`
  [44cfe95a] Pkg `@stdlib/Pkg`
  [9a3f8284] Random `@stdlib/Random`
  [6462fe0b] Sockets `@stdlib/Sockets`
  [8dfed614] Test `@stdlib/Test`
      Status `/tmp/jl_zsgJnf/Manifest.toml`
  [fbe9abb3] AWS v1.61.0
  [1c724243] AWSS3 v0.9.2
  [79e6a3ab] Adapt v3.3.1
  [a74b3585] Blosc v0.7.1
  [944b1d66] CodecZlib v0.7.0
  [34da2185] Compat v3.40.0
  [8f4d0f93] Conda v1.5.2
  [864edb3b] DataStructures v0.18.10
  [3c3547ce] DiskArrays v0.2.12
  [e2ba6199] ExprTools v0.1.6
  [8f5d6c58] EzXML v1.1.0
  [48062228] FilePathsBase v0.9.14
  [bc5e4493] GitHub v5.7.0
  [cd3eb016] HTTP v0.9.16
  [83e8ac13] IniFile v0.5.0
  [c8e1da08] IterTools v1.3.0
  [692b3bcd] JLLWrappers v1.3.0
  [682c06a0] JSON v0.21.2
  [8ac3fa9e] LRUCache v1.3.0
  [1914dd2f] MacroTools v0.5.9
  [739be429] MbedTLS v1.0.3
  [4281f0d9] Minio v0.1.2
  [78c3b35d] Mocking v0.7.3
  [6fe1bfb0] OffsetArrays v1.10.8
  [bac558e1] OrderedCollections v1.4.1
  [69de0a69] Parsers v2.1.2
  [21216c6a] Preferences v1.2.2
  [438e738f] PyCall v1.92.5
  [20febd7b] Retry v0.4.1
  [2133526b] SodiumSeal v0.1.1
  [2da68c74] SymDict v0.3.0
  [3bb67fe8] TranscodingStreams v0.9.6
  [5c2747f8] URIs v1.3.0
  [81def892] VersionParsing v1.2.1
  [228000da] XMLDict v0.4.1
  [0a941bbe] Zarr v0.7.0 `~/.julia/dev/Zarr`
  [0b7ba130] Blosc_jll v1.21.0+0
  [94ce4f54] Libiconv_jll v1.16.1+1
  [5ced341a] Lz4_jll v1.9.3+0
  [02c8fc9c] XML2_jll v2.9.12+0
  [3161d3a3] Zstd_jll v1.5.0+0
  [a9144af2] libsodium_jll v1.0.20+0
  [0dad84c5] ArgTools `@stdlib/ArgTools`
  [56f22d72] Artifacts `@stdlib/Artifacts`
  [2a0f44e3] Base64 `@stdlib/Base64`
  [ade2ca70] Dates `@stdlib/Dates`
  [8bb1440f] DelimitedFiles `@stdlib/DelimitedFiles`
  [8ba89e20] Distributed `@stdlib/Distributed`
  [f43a241f] Downloads `@stdlib/Downloads`
  [b77e0a4c] InteractiveUtils `@stdlib/InteractiveUtils`
  [b27032c2] LibCURL `@stdlib/LibCURL`
  [76f85450] LibGit2 `@stdlib/LibGit2`
  [8f399da3] Libdl `@stdlib/Libdl`
  [37e2e46d] LinearAlgebra `@stdlib/LinearAlgebra`
  [56ddb016] Logging `@stdlib/Logging`
  [d6f4376e] Markdown `@stdlib/Markdown`
  [a63ad114] Mmap `@stdlib/Mmap`
  [ca575930] NetworkOptions `@stdlib/NetworkOptions`
  [44cfe95a] Pkg `@stdlib/Pkg`
  [de0858da] Printf `@stdlib/Printf`
  [3fa0cd96] REPL `@stdlib/REPL`
  [9a3f8284] Random `@stdlib/Random`
  [ea8e919c] SHA `@stdlib/SHA`
  [9e88b42a] Serialization `@stdlib/Serialization`
  [1a1011a3] SharedArrays `@stdlib/SharedArrays`
  [6462fe0b] Sockets `@stdlib/Sockets`
  [2f01184e] SparseArrays `@stdlib/SparseArrays`
  [10745b16] Statistics `@stdlib/Statistics`
  [fa267f1f] TOML `@stdlib/TOML`
  [a4e569a6] Tar `@stdlib/Tar`
  [8dfed614] Test `@stdlib/Test`
  [cf7118a7] UUIDs `@stdlib/UUIDs`
  [4ec0a83e] Unicode `@stdlib/Unicode`
  [deac9b47] LibCURL_jll `@stdlib/LibCURL_jll`
  [29816b5a] LibSSH2_jll `@stdlib/LibSSH2_jll`
  [c8ffd9c3] MbedTLS_jll `@stdlib/MbedTLS_jll`
  [14a3606d] MozillaCACerts_jll `@stdlib/MozillaCACerts_jll`
  [83775a58] Zlib_jll `@stdlib/Zlib_jll`
  [8e850ede] nghttp2_jll `@stdlib/nghttp2_jll`
  [3f19e933] p7zip_jll `@stdlib/p7zip_jll`
     Testing Running tests...
Type                : ZArray
Data type           : Vector{Float64}
Shape               : (2, 3)
Chunk Shape         : (2, 3)
Order               : C
Read-Only           : false
Compressor          : Zarr.BloscCompressor(0, 5, "lz4", true)
Filters             : (Zarr.VLenArrayFilter{Float64}(),)
Store type          : Dictionary Storage
No. bytes           : unknown
No. bytes stored    : 108
Storage ratio       : unknown
Chunks initialized  : 1/1
[ Info: Minio server started
GCS S3 Storage: Error During Test at /home/abarth/.julia/dev/Zarr/test/storage.jl:129
  Test threw exception
  Expression: storagesize(cmip6, p) == 16098
  MethodError: no method matching haskey(::String, ::String)
  Closest candidates are:
    haskey(::Base.BinaryPlatforms.AbstractPlatform, ::String) at binaryplatforms.jl:138
    haskey(::IOContext, ::Any) at show.jl:338
    haskey(::LRUCache.LRU, ::Any) at /home/abarth/.julia/packages/LRUCache/44dJX/src/LRUCache.jl:55
    ...
  Stacktrace:
   [1] storagesize(s::S3Store, p::String)
     @ Zarr ~/.julia/dev/Zarr/src/Storage/s3store.jl:49
   [2] macro expansion
     @ ~/.julia/dev/Zarr/test/storage.jl:129 [inlined]
   [3] macro expansion
     @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1151 [inlined]
   [4] top-level scope
     @ ~/.julia/dev/Zarr/test/storage.jl:128
GCS S3 Storage: Error During Test at /home/abarth/.julia/dev/Zarr/test/storage.jl:127
  Got exception outside of a @test
  Unexpected character
  Line: 0
  Around: ...<HTML><HEAD><meta http...
              ^
  
  Stacktrace:
    [1] error(s::String)
      @ Base ./error.jl:33
    [2] _error(message::String, ps::JSON.Parser.MemoryParserState)
      @ JSON.Parser ~/.julia/packages/JSON/QXB8U/src/Parser.jl:140
    [3] parse_jsconstant(#unused#::JSON.Parser.ParserContext{Dict{String, Any}, Int64, true, nothing}, ps::JSON.Parser.MemoryParserState)
      @ JSON.Parser ~/.julia/packages/JSON/QXB8U/src/Parser.jl:193
    [4] parse_value(pc::JSON.Parser.ParserContext{Dict{String, Any}, Int64, true, nothing}, ps::JSON.Parser.MemoryParserState)
      @ JSON.Parser ~/.julia/packages/JSON/QXB8U/src/Parser.jl:170
    [5] parse(str::String; dicttype::Type, inttype::Type{Int64}, allownan::Bool, null::Nothing)
      @ JSON.Parser ~/.julia/packages/JSON/QXB8U/src/Parser.jl:450
    [6] parse
      @ ~/.julia/packages/JSON/QXB8U/src/Parser.jl:448 [inlined]
    [7] Zarr.Metadata(s::String)
      @ Zarr ~/.julia/dev/Zarr/src/metadata.jl:169
    [8] getmetadata(s::S3Store, p::String)
      @ Zarr ~/.julia/dev/Zarr/src/Storage/Storage.jl:88
    [9] ZArray(s::S3Store, mode::String, path::String)
      @ Zarr ~/.julia/dev/Zarr/src/ZArray.jl:102
   [10] zopen_noerr(s::S3Store, mode::String; consolidated::Bool, path::String, lru::Int64)
      @ Zarr ~/.julia/dev/Zarr/src/ZGroup.jl:42
   [11] #zopen#81
      @ ~/.julia/dev/Zarr/src/ZGroup.jl:81 [inlined]
   [12] macro expansion
      @ ~/.julia/dev/Zarr/test/storage.jl:130 [inlined]
   [13] macro expansion
      @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1151 [inlined]
   [14] top-level scope
      @ ~/.julia/dev/Zarr/test/storage.jl:128
   [15] include(fname::String)
      @ Base.MainInclude ./client.jl:444
   [16] macro expansion
      @ ~/.julia/dev/Zarr/test/runtests.jl:227 [inlined]
   [17] macro expansion
      @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1151 [inlined]
   [18] top-level scope
      @ ~/.julia/dev/Zarr/test/runtests.jl:17
   [19] include(fname::String)
      @ Base.MainInclude ./client.jl:444
   [20] top-level scope
      @ none:6
   [21] eval
      @ ./boot.jl:360 [inlined]
   [22] exec_options(opts::Base.JLOptions)
      @ Base ./client.jl:261
   [23] _start()
      @ Base ./client.jl:485
Test Summary:                    | Pass  Error  Total
Zarr                             |  420      2    422
  ZArray                         |   31            31
  Groups                         |    5             5
  Metadata                       |   38            38
  getindex/setindex              |    9             9
  resize                         |   11            11
  string array getindex/setindex |    4             4
  ragged arrays                  |    5             5
  Path Normalization             |    5             5
  DirectoryStore                 |   24            24
  DictStore                      |   20            20
  LRU                            |   10            10
  Minio S3 storage               |   18            18
  AWS S3 Storage                 |    5             5
  GCS S3 Storage                 |           2      2
  HTTP Storage                   |    3             3
  Python zarr implementation     |  210           210
  Python datetime types          |   22            22
ERROR: LoadError: Some tests did not pass: 420 passed, 0 failed, 2 errored, 0 broken.
in expression starting at /home/abarth/.julia/dev/Zarr/test/runtests.jl:14
ERROR: Package Zarr errored during testing

julia> cd(expanduser("~/.julia/dev/Zarr")) do; run(`git log --pretty=oneline -5`); end
bbdc21a7b15d4fdcd124addcdb370c3e2b69f70d (HEAD -> master, origin/master, origin/HEAD) CompatHelper: add new compat entry for LRUCache at version 1, (keep existing compat) (#70)
1d83c09455cf966b1ab1760b15e847aa74db75c0 Implement an LRUcache for decoded chunks (#69)
686e41856808d71c7cd878f0c6d142a89c60be37 Rewrite the storage interface (#66)
5c49cc2e7715071a82e38a10ca82a9a7323bd747 (tag: v0.6.3) Update Project.toml
21679fae0590e58b3da19b54b6955e1a0f85b921 Add create option to storefromstring (#60)
Process(`git log --pretty=oneline -5`, ProcessExited(0))
```

**Comment by meggart** [comment]
I had to downgrade AWS.jl for some reason, because I saw an error after an update. Is this still the reason?

**Comment by meggart** [comment]
Same for me, the tests for master fail locally, this is strange...

**Comment by Alexander-Barth** [comment]
Here is the HTML document that it returned when one downloads the `.zarray` objects using the `gs://` protocol:

```html
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="https://storage.googleapis.com/cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/highresSST-present/r1i1p1f1/6hrPlev/psl/gn/v20170706/.zarray">here</A>.
</BODY></HTML>
```

**Comment by Alexander-Barth** [comment]
Interestingly, from within the pangeo cloud, both schemes do work:

```julia
Zarr.storefromstring("gs://cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/highresSST-present/r1i1p1f1/6hrPlev/psl/gn/v20170706/"), # works                    
Zarr.storefromstring(GCStore,"gs://cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/highresSST-present/r1i1p1f1/6hrPlev/psl/gn/v20170706/",false), # works       
```

**Comment by meggart** [comment]
I did some more digging and found the reason. Some changed in the internals of GCS so that when trying to access a non-existent object from GCS from the outside, a 301 error is returned, which is not recognized by AWS and does not throw an error. I have a fix for this, but for now I would just merge your PR and then try a bit if we really need this fix or if we can move to your implementation entirely.

**Comment by Alexander-Barth** [comment]
Thanks for merging it!

**Pull request merged**
